### ISSUE TITLE
nd2reader with NIS 3 InvalidVersionError

### ISSUE THREAD

**Issue by fabienjammes** [rbnvrw/nd2reader#5]
Dear all,

I am new to python. I have the NIS software on my microscope computer but it is the version 3.
I am trying to use the nd2reader package to open my nd2 files.
However, I get this error:

  File "C:\Users\jammes\Anaconda3\envs\PhD_FJ_Python\lib\site-packages\nd2reader\parser.py", line 129, in _check_version_supported
    raise InvalidVersionError("No parser is available for that version.")

InvalidVersionError: No parser is available for that version.

I guess it is because it is a nd2 file from NIS 3 instead of NIS4.

Is there any fix to that ?

Thanks in advance :)

**Comment by rbnvrw** [comment]
Dear @fabienjammes, thank you for the report.

Yes, this is because the software only officially supports NIS4 files.
I do not know if it will also work on NIS3 files, however:

I have removed the error and replaced it by a printed warning in version 3.0.9 (install from GitHub/pip, conda version is not yet updated).
That way you can test whether it works for your nd2 files, and report back here so I can either close this issue or help you.

Thanks!

**Comment by rbnvrw** [comment]
@fabienjammes can I close this issue or do you still have problems?
